### ISSUE TITLE
Error when running tutorial

### ISSUE THREAD

**Issue by andreashlarsen** [rogautier/packmem#2] opened 2024-03-06 10:56 UTC
I tried to run the tutorial (https://packmem.ipmc.cnrs.fr/tuto.html). 

when running the bash script: 
```
bash ScriptPackMem.sh
```
I get this error: 
```
Wed 06 Mar 2024 11:39:07 AM CET: PackMem running on pdb/membrane0.pdb
ERROR : Association of lipid DOE and atom C210 not found in parameter file
ERROR : Association of lipid DOE and atom C210 not found in parameter file
ERROR : Association of lipid DOE and atom C210 not found in parameter file
cat: membrane0_Up_Deep_result.txt: No such file or directory
cat: membrane0_Lo_Deep_result.txt: No such file or directory
cat: membrane0_Up_Shallow_result.txt: No such file or directory
cat: membrane0_Lo_Shallow_result.txt: No such file or directory
cat: membrane0_Up_All_result.txt: No such file or directory
cat: membrane0_Lo_All_result.txt: No such file or directory
Wed 06 Mar 2024 11:39:08 AM CET: PackMem running on pdb/membrane1.pdb
ERROR : Association of lipid DOE and atom C210 not found in parameter file
ERROR : Association of lipid DOE and atom C210 not found in parameter file
ERROR : Association of lipid DOE and atom C210 not found in parameter file
cat: membrane1_Up_Deep_result.txt: No such file or directory
cat: membrane1_Lo_Deep_result.txt: No such file or directory
cat: membrane1_Up_Shallow_result.txt: No such file or directory
cat: membrane1_Lo_Shallow_result.txt: No such file or directory
cat: membrane1_Up_All_result.txt: No such file or directory
cat: membrane1_Lo_All_result.txt: No such file or directory
```

In the bash script, I only changed path name, prefix and set number of frames to 1 instead of 400 . 
In PackMem.py, I only changed name of python interpreter from usr/bin/python to usr/bin/python3
 
The error comes from matrix.py:
 
```
# get radius from [Lipid_name Atom_name]
def get_radius(radius, res_name, atom_name):
    key = res_name+" "+atom_name
    if key not in radius.keys():
        print("ERROR : Association of lipid %s and atom %s not found in parameter file"%(res_name, atom_name))
        sys.exit()
    return radius[key]
```
I hope you could provide some help on how to fix this. I think PackMem could be useful for our research project, but If the tutorial is not running, I am afraid that I cannot make it work for my own system.

**Comment by patrickfuchs** [comment] 2024-05-14 12:05
Hi @andreashlarsen, sorry I forgot to come back to you. My Ph.D student Maya will answer to day on how to fix this.

**Comment by MayaZygadlo** [comment] 2024-05-14 12:15
Hi, the problem comes from the difference between the PackMem parameter file
vdw_radii_Charmm.txt (I'm assuming you are using the CHARMM force field) and the
pdb file that you created for PackMem in the naming of the atom.

Here is the line that causes the problem in the vdw_radii_Charmm.txt :
DOE  0C21 2.10 a
And here is the line in one of your pdb file :
ATOM     56 C210 DOPEA   1      45.520  44.680  46.870  1.00  0.00           C

As you can see, PackMem expects the atom name to be 0C21 but yours is named C210.
Note that this will be the case for all the atom names longer than 3 characters.
In order to solve this problem, there is two ways to go about this :
Either you change all the atom names in the pdb files created for PackMem (long
and not recommended), or you change the parameter file vdw_radii_Charmm.txt to
match the names you have in your pdb file.

I hope this explanation was clear enough. Do not hesitate to contact us again if
you encounter other problems with the program.
Thank you,
Maya

**Comment by patrickfuchs** [comment] 2024-05-14 12:21
@rogautier, now that gmx trjconv produces neat pdb files (e.g. atom name C210 is written "C210" and not "0C21"), maybe we could change the vdw_radii files? We will propose a PR to fix this.

**Comment by patrickfuchs** [comment] 2024-05-27 15:08
@andreashlarsen,  the problem is now fixed, you can git pull to get the last version.

**Closed by patrickfuchs** 2024-05-27 15:08 UTC

**Comment by andreashlarsen** [comment] 2024-05-27 20:55
thank you for fixing this!
